import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: "#f8f4ec",
        ink: "#2f2f2f",
        mist: "#eee7db",
        charcoal: "#474747",
        smoke: "#8c857c",
        "primary-container": "#111827",
        "on-primary-container": "#6b7280",
        "on-primary-fixed-variant": "#4b5563",
        "on-primary-fixed": "#111827",
        "primary-fixed": "#e5e7eb",
        "primary-fixed-dim": "#d1d5db",
        "inverse-primary": "#d1d5db",
        secondary: "#0f9f6e",
        "secondary-container": "#0b7a58",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#f4fffb",
        "secondary-fixed": "#d6f5e9",
        "secondary-fixed-dim": "#a7e8ce",
        "on-secondary-fixed": "#062f21",
        "on-secondary-fixed-variant": "#0a684b",
        tertiary: "#000000",
        "tertiary-container": "#0b6b4d",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#0b6b4d",
        "tertiary-fixed": "#c8f5e1",
        "tertiary-fixed-dim": "#9fe8ca",
        "on-tertiary-fixed": "#073525",
        "on-tertiary-fixed-variant": "#0b6b4d",
        surface: "#f8f4ec",
        "surface-dim": "#e8ece8",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f7f7f5",
        "surface-container": "#eef1ed",
        "surface-container-high": "#e7ebe6",
        "surface-container-highest": "#dfe5df",
        "surface-variant": "#d9dfd9",
        "surface-tint": "#4b5563",
        "on-surface": "#111827",
        "on-surface-variant": "#4b5563",
        "on-background": "#111827",
        "inverse-surface": "#1f2937",
        "inverse-on-surface": "#f9fafb",
        outline: "#8a938d",
        "outline-variant": "#d3d8d3",
        error: "#b42318",
        "error-container": "#fde7e2",
        "on-error": "#ffffff",
        "on-error-container": "#7a271a",
        background: "#f8f4ec",
        primary: "#2f2f2f",
        "on-primary": "#ffffff",
      },
      boxShadow: {
        float: "0 24px 60px -34px rgba(47, 47, 47, 0.22)",
        card: "0 16px 42px -26px rgba(47, 47, 47, 0.18)",
        ambient: "0 24px 48px rgba(17, 24, 39, 0.08)",
        "ambient-sm": "0 24px 48px rgba(17, 24, 39, 0.04)",
        nav: "24px 0 48px rgba(17, 24, 39, 0.08)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
        "4xl": "2rem",
      },
      fontFamily: {
        sans: ['"Libre Baskerville"', "Georgia", "serif"],
        serif: ['"Libre Baskerville"', "Georgia", "serif"],
      },
    },
  },
  plugins: [],
};

export default config;
